import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import { Sofia_Sans} from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Scroll from '@/components/Scroll'
import { Toaster } from '@/components/ui/toaster'




const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600', '700', '800'] })
const sofia = Sofia_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Self Made Devs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (    
    <html lang="en">
      <body className={sofia.className}>
        <Navbar />
        <Scroll />
            {children}
            <Toaster />
      </body>
    </html>
    
    
    
    
  )
}
