import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import { Sofia_Sans} from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Scroll from '@/components/scroll'
import { Toaster } from '@/components/ui/toaster'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import Footer from '@/components/footer'
import { ToastProvider } from '@/components/providers/toaster-provider'


const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600', '700', '800'] })
const sofia = Sofia_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Self Made Devs',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  const session = await auth()
  return (   
   <SessionProvider session={session}>
    <html lang="en">
      <body className={sofia.className}>
      <Navbar />
        <Scroll />
            {children}
            <ToastProvider />
      <Footer />
      </body>
    </html>
    </SessionProvider>
    
    
    
    
    
  )
}
